---
- name: Mettre à jour le code source de la Lambda
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Zipper le handler Python
      community.general.archive:
        path: ../lambda/handler.py
        dest: ../lambda/deployment_package.zip
        format: zip

    - name: Mettre à jour la fonction via amazon.aws collection
      amazon.aws.lambda_function:
        name: "image_to_pdf_processor"
        state: present
        zip_file: "../lambda/deployment_package.zip"
