---
- name: Mettre à jour le code source de la Lambda
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Zipper le dossier Lambda complet
      community.general.archive:
        path: ../lambda/*
        dest: ../lambda/deployment_package.zip
        format: zip
        mode: '0644'

    - name: Mettre à jour la fonction via amazon.aws collection
      amazon.aws.lambda: # noqa args
        name: "image_to_pdf_processor"
        state: present
        zip_file: "../lambda/deployment_package.zip"
